channels:
  - conda-forge

dependencies:
  - altair>=5.5.0          # from uv.lock
  - jhsingle-native-proxy>=0.8.2
  - pandas>=2.3.0          # from uv.lock
  - streamlit>=1.45.1      # from uv.lock
  - ipykernel
  - anthropic>=0.54.0      # from uv.lock
  - graphviz>=0.21         # from uv.lock
  - langchain-core>=0.3.64 # from uv.lock
  - langchain-openai>=0.3.22
  - transformers>=4.52.4
